import type { Account } from '../types/types'

export const mockAccounts: Account[] = [
  {
    id: 1,
    code: "ACC001",
    title: "Возврат от поставщика",
    description: "Возврат товара от поставщика due to брак или пересорт",
    type: "income",
    category: "supplier",
    image: "",
    inCart: false,
    isActive: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z"
  },
  {
    id: 2,
    code: "ACC002",
    title: "Оплата аренды офиса",
    description: "Ежемесячная оплата аренды офисного помещения",
    type: "expense",
    category: "rent",
    image: "/images/office-rent.jpg",
    inCart: true,
    isActive: true,
    createdAt: "2024-01-10T09:30:00Z",
    updatedAt: "2024-01-10T09:30:00Z"
  },
  {
    id: 3,
    code: "ACC003",
    title: "Закупка оборудования",
    description: "Покупка нового компьютерного оборудования для сотрудников",
    type: "expense",
    category: "equipment",
    image: "/images/equipment.jpg",
    inCart: false,
    isActive: true,
    createdAt: "2024-01-08T14:20:00Z",
    updatedAt: "2024-01-08T14:20:00Z"
  },
  {
    id: 4,
    code: "ACC004",
    title: "Поступление от клиента",
    description: "Оплата за выполненные работы от постоянного клиента",
    type: "income",
    category: "client_payment",
    image: "/images/client-payment.jpg",
    inCart: false,
    isActive: true,
    createdAt: "2024-01-12T11:45:00Z",
    updatedAt: "2024-01-12T11:45:00Z"
  },
  {
    id: 5,
    code: "ACC005",
    title: "Коммунальные платежи",
    description: "Оплата электроэнергии, воды и интернета",
    type: "expense",
    category: "utilities",
    image: "",
    inCart: true,
    isActive: true,
    createdAt: "2024-01-05T08:15:00Z",
    updatedAt: "2024-01-05T08:15:00Z"
  },
  {
    id: 6,
    code: "ACC006",
    title: "Продажа товара",
    description: "Реализация товара со склада",
    type: "income",
    category: "sales",
    image: "/images/sales.jpg",
    inCart: false,
    isActive: true,
    createdAt: "2024-01-18T16:30:00Z",
    updatedAt: "2024-01-18T16:30:00Z"
  },
  {
    id: 7,
    code: "ACC007",
    title: "Заработная плата",
    description: "Выплата заработной платы сотрудникам",
    type: "expense",
    category: "salary",
    image: "/images/salary.jpg",
    inCart: false,
    isActive: true,
    createdAt: "2024-01-25T12:00:00Z",
    updatedAt: "2024-01-25T12:00:00Z"
  },
  {
    id: 8,
    code: "ACC008",
    title: "Инвестиционный доход",
    description: "Дивиденды от инвестиций в ценные бумаги",
    type: "income",
    category: "investment",
    image: "/images/investment.jpg",
    inCart: false,
    isActive: true,
    createdAt: "2024-01-30T10:20:00Z",
    updatedAt: "2024-01-30T10:20:00Z"
  },
  {
    id: 9,
    code: "ACC009",
    title: "Рекламная кампания",
    description: "Расходы на проведение рекламной кампании",
    type: "expense",
    category: "marketing",
    image: "/images/marketing.jpg",
    inCart: true,
    isActive: true,
    createdAt: "2024-01-22T13:10:00Z",
    updatedAt: "2024-01-22T13:10:00Z"
  },
  {
    id: 10,
    code: "ACC010",
    title: "Возврат налогов",
    description: "Возврат НДС по экспортным операциям",
    type: "income",
    category: "tax_refund",
    image: "/images/tax-refund.jpg",
    inCart: false,
    isActive: true,
    createdAt: "2024-01-28T15:45:00Z",
    updatedAt: "2024-01-28T15:45:00Z"
  }
]